apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-db
    app.dbc.dk/team: metascrum
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: nothing
  name: test-db
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: test-db
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-db
        app.dbc.dk/team: metascrum
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: nothing
        network-policy-postgres-incoming: 'yes'
    spec:
      dnsConfig:
        searches:
          - dbc.dk
      containers:
      - image:  docker-dbc.artifacts.dbccloud.dk/dbc-postgres-15:latest
        name: hazelcast-fun-service
        resources:
          requests:
            cpu: "0.1"
            memory: "2Gi"
        ports:
        - {containerPort: 5432, protocol: TCP}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-db
    app.dbc.dk/team: metascrum
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: nothing
  name: test-db
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector: {app: test-db}
  type: ClusterIP
